#!/usr/bin/env bash
#This is a script that transfers a file from our client to a server

if [ $# -eq 4 ]
then
scp -o StrictHostKeyChecking=no $1 $3@$2:/~/ -i $4
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

fi
