#!/usr/bin/env bash
#This is a script that transfers a file from our client to a server

if [ $# -ne 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else

scp -i $1  -D $2 -J ~/

fi
