#!/usr/bin/env bash
#This script installs nginx and configures it
sudo apt-get -y install nginx 
sudo ufw allow 'Nginx HTTP'
sudo ufw allow "OpenSSH"
sudo ufw enable
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'
