#!/usr/bin/env bash
# install nginx web-server

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
redirect="rewrite ^/redirect_me https://youtu.be/kx4RTBZFAYU permanent;"
sudo sed -i "26i/$redirect" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload